program avr_arm;
uses
  Forms,
  Windows,
  MainForm in 'MainForm.pas' {frm_Main},
  OrderForm in 'OrderForm.pas' {frm_Order},
  shiftnumform in 'shiftnumform.pas' {frm_ShiftNum},
  DModule in 'DModule.pas' {DM_Main: TDataModule},
  WarningForm in 'WarningForm.pas' {frm_Warning},
  GlobalData in 'GlobalData.pas',
  TemperatureForm in 'TemperatureForm.pas' {frm_Temperature},
  SearchOrderByNumber in 'SearchOrderByNumber.pas' {frm_SearchOrderByNumber},
  LoginForm in 'LoginForm.pas' {frm_Login},
  EquipmentForm in 'EquipmentForm.pas' {frm_Equipment},
  EquipPlannedForm in 'EquipPlannedForm.pas' {frm_EquipPlanned},
  AboutForm in 'AboutForm.pas' {AboutFrm},
  XLConst in 'XLCONST.PAS',
  PrintPreviewChartForm in 'PrintPreviewChartForm.pas' {PrintPreviewChartFrm},
  PrinterWorks in 'PrinterWorks.pas',
  StringConsts in 'StringConsts.pas',
  ExcelWorksForm in 'ExcelWorksForm.pas',
  DgrForm in 'DGRFORM.pas' {Graph},
  AN_DIAGR in 'AN_DIAGR.pas' {QueryForm},
  HelpFunctions in 'HelpFunctions.pas',
  BaseGridForm in 'BaseGridForm.pas' {frm_BaseGrid},
  BoltsForm in 'BoltsForm.pas' {frm_Bdmolts},
  ExcavationsForm in 'ExcavationsForm.pas' {frm_Excavations},
  BaseVocForm in 'BaseVocForm.pas' {frm_BaseV|oc},
  VocOfficialsForm in 'VocOfficialsForm.pas' {frm_VocOfficials},
  VocBrigadiersForm in 'VocBrigadiersForm.pas' {frm_VocBrigadiers},
  VocTubeMaterialForm in 'VocTubeMaterialForm.pas' {frm_VocTubeMaterial},
  VocTubeDiameterForm in 'VocTubeDiameterForm.pas' {frm_VocTubeDiameter},
  VocDamageLocalityForm in 'VocDamageLocalityForm.pas' {frm_VocDamageLocality},
  VocDamagePlaceForm in 'VocDamagePlaceForm.pas' {frm_VocDamagePlace},
  VocProfWorksForm in 'VocProfWorksForm.pas' {frm_VocProfWorks},
  VocMessageTypesForm in 'VocMessageTypesForm.pas' {frm_VocMessageTypes},
  VocEquipmentForm in 'VocEquipmentForm.pas' {frm_VocEquipment},
  VocOrganizationsForm in 'VocOrganizationsForm.pas' {frm_VocOrganizations},
  VocRegionsForm in 'VocRegionsForm.pas' {frm_VocRegions},
  VocMaterialsForm in 'VocMaterialsForm.pas' {frm_VocMaterials},
  VocStreetsForm in 'VocStreetsForm.pas' {frm_VocStreets},
  SelectItemForm in 'SelectItemForm.pas' {frm_SelectItem},
  UniversalSearchForm in 'UniversalSearchForm.pas' {frm_UniversalSearch},
  PeriodRegDmgSelForm in 'PeriodRegDmgSelForm.pas' {frm_PeriodRegDmgSel},
  ReportManager in 'ReportManager.pas' {DM_ReportManager: TDataModule},
  PeriodRegDmgAdresForm in 'PeriodRegDmgAdresForm.pas' {frm_PeriodRegDmgAdresSel},
  DateDmgSelForm in 'DateDmgSelForm.pas' {frm_DateDmgSel},
  PeriodCloseRegDmgSelForm in 'PeriodCloseRegDmgSelForm.pas' {frm_PeriodCloseRegDmgSel},
  PeriodCloseDmgExcSelForm in 'PeriodCloseDmgExcSelForm.pas' {frm_PeriodCloseDmgExcSel},
  SmenaRegDmgSelForm in 'SmenaRegDmgSelForm.pas' {frm_SmenaRegDmgSel},
  DateSelForm in 'DateSelForm.pas' {frm_DateSel},
  PeriodMsgSelForm in 'PeriodMsgSelForm.pas' {frm_PeriodMsgSel},
  PeriodRegBlagSelForm in 'PeriodRegBlagSelForm.pas' {frm_PeriodRegBlagSel},
  AnalysisManager in 'AnalysisManager.pas' {DM_AnalysisManager: TDataModule},
  TemperSvodForm in 'TemperSvodForm.pas' {frm_TemperSvod},
  DatesSelForm in 'DatesSelForm.pas' {frm_DatesSel},
  AnalysisViewForm in 'AnalysisViewForm.pas' {frm_AnalysisView},
  UnChartForm in 'UnChartForm.pas' {frm_Chart},
  DmgChartForm in 'DmgChartForm.pas' {frm_DmgChart},
  RegionDamageCount in 'RegionDamageCount.pas',
  DmgChartSettingForm in 'DmgChartSettingForm.pas' {frm_DmgChartSetting},
  PeriodRegDmgDiamSelForm in 'PeriodRegDmgDiamSelForm.pas' {frm_PeriodRegDmgDiamSel},
  MiniUniversalSelForm in 'MiniUniversalSelForm.pas' {frm_MiniUniversalSel},
  PeriodTimeRegDmgSelForm in 'PeriodTimeRegDmgSelForm.pas' {frm_PeriodTimeRegDmgSel},
  AnLeakOptSelForm in 'AnLeakOptSelForm.pas' {frm_AnLeakOptSel},
  AnLeakLocSelForm in 'AnLeakLocSelForm.pas' {frm_AnLeakLocSel},
  AnLeakDiamSelForm in 'AnLeakDiamSelForm.pas' {frm_AnLeakDiamSel},
  LeakDiamChartForm in 'LeakDiamChartForm.pas' {frm_LeakDiamChart},
  AnLeakDaysSelForm in 'AnLeakDaysSelForm.pas' {frm_AnLeakDaysSel},
  AVR_Analysis in 'AVR_Analysis.pas',
  BaseOptionForm in 'BaseOptionForm.pas' {frm_BaseOption},
  BaseResultForm in 'BaseResultForm.pas' {frm_BaseResult},
  Analysis_HelpClasses in 'Analysis_HelpClasses.pas',
  AnLeakTimeSelForm in 'AnLeakTimeSelForm.pas' {frm_AnLeakTimeSel},
  AnBrigDepSelForm in 'AnBrigDepSelForm.pas' {frm_AnBrigDepSel},
  AnDateDmgEquipSelForm in 'AnDateDmgEquipSelForm.pas' {frm_AnDateDmgEquipSel},
  ComingClosedEquipChartForm in 'ComingClosedEquipChartForm.pas' {frm_ComingClosedEquipChart},
  AVR_Report in 'AVR_Report.pas',
  DataSetTree in 'DataSetTree.pas',
  GridViewBuilder in 'GridViewBuilder.pas',
  CustomReport in 'CustomReport.pas',
  PeriodRegPlaceTypeSel in 'PeriodRegPlaceTypeSel.pas' {frm_PeriodRegPlaceTypeSel},
  PeriodRegSelForm in 'PeriodRegSelForm.pas' {frm_PeriodRegSel},
  ChartMarkForm in 'ChartMarkForm.pas' {frm_ChartMark},
  HelpClasses in 'HelpClasses.pas',
  ExcSpreadSheet in 'ExcSpreadSheet.pas' {fmExcSprSheet},
  PeriodExcSpredSelForm in 'PeriodExcSpredSelForm.pas' {frm_PeriodExcSpreadSel},
  WaitProcessForm in 'WaitProcessForm.pas' {frm_WaitProcess},
  FrPreviewForm in 'FrPreviewForm.pas' {frm_FrPreview},
  BaseFrPreviewForm in 'BaseFrPreviewForm.pas' {frm_BaseFrPreview},
  IB_Reports in 'IB_Reports.pas',
  KolvoOtkazForm in 'KolvoOtkazForm.pas' {frm_KolvoOtkazOpt},
  KolvoOtkazGraphForm in 'KolvoOtkazGraphForm.pas' {frm_KolvoOtkazGraph},
  SvodkaGikForm in 'SvodkaGikForm.pas' {frm_SvodkaGik},
  NGReportManager in 'NGReportManager.pas',
  NGBaseReport in 'NGBaseReport.pas',
  NGReports in 'NGReports.pas',
  SvodkaGikDModule in 'SvodkaGikDModule.pas' {dm_SvodkaGik: TDataModule},
  ApplicationSettings in 'ApplicationSettings.pas',
  UtechkiNaVodosetiOptForm in 'UtechkiNaVodosetiOptForm.pas' {frm_UtechkiNaVodosetiOpt},
  UtechkiNaVodosetiDModule in 'UtechkiNaVodosetiDModule.pas' {dm_UtechkiNaVodoseti: TDataModule},
  UtechkiNaVodosetiRes in 'UtechkiNaVodosetiRes.pas' {frm_UtechkiNaVodosetiRes},
  NGReportBaseDModule in 'NGReportBaseDModule.pas' {dm_NGReportBase: TDataModule},
  StDispDModule in 'StDispDModule.pas' {DM_StDisp: TDataModule},
  VAbonBezVodyDModule in 'VAbonBezVodyDModule.pas' {dm_VAbonBezVody: TDataModule},
  NotePadForm in 'NotePadForm.pas' {frm_NotePad},
  AddPrintDModule in 'AddPrintDModule.pas' {dm_AddPrint: TDataModule},
  RootReport in 'RootReport.pas',
  RootReportDModule in 'RootReportDModule.pas' {dm_RootReport: TDataModule},
  MenuManager in 'MenuManager.pas',
  AddOrderInfoForm in 'AddOrderInfoForm.pas' {frm_AddOrderInfo},
  Previnst in 'Previnst.pas',
  UniSearchResultForm in 'UniSearchResultForm.pas' {frm_UniSearchResult},
  UniversalSearch2DModule in 'UniversalSearch2DModule.pas' {dm_UniversalSearch2: TDataModule},
  VocManager in 'VocManager.pas',
  ZastavkaForm in 'ZastavkaForm.pas' {frm_Zastavka},
  OrderNumberForm in 'OrderNumberForm.pas' {frm_OrderNumber},
  OrderShortInfoForm in 'OrderShortInfoForm.pas' {frm_OrderShortInfo},
  SecurityBaseForm in 'SecurityBaseForm.pas' {frm_SecurityBase},
  RightsManagerDModule in 'RightsManagerDModule.pas' {DM_RightsManager: TDataModule},
  AvrUserManagerDModule in 'AvrUserManagerDModule.pas' {dm_AvrUserManager: TDataModule},
  AvrUserManagerForm in 'AvrUserManagerForm.pas' {frm_AvrUserManager},
  AvrUserMgrLoginForm in 'AvrUserMgrLoginForm.pas' {frm_AvrUserMgrLogin},
  AddUserForm in 'AddUserForm.pas' {frm_AddUser},
  SetPwdForm in 'SetPwdForm.pas' {frm_SetPwd},
  AppGUIDS in 'AppGUIDS.pas',
  AppLoginer in 'AppLoginer.pas',
  SvodVedPrintDateForm in 'SvodVedPrintDateForm.pas' {frm_SvodVedPrintDate},
  FrPrintDM in 'FrPrintDM.pas' {DM_Print: TDataModule},
  OrderInfoForm in 'OrderInfoForm.pas' {frm_OrderInfo},
  print_image in 'print_image.pas' {PrintImage},
  FillReportManager in 'FillReportManager.pas' {DM_FillReportManager: TDataModule},
  MemCheck in 'MemCheck.pas',
  SvodVedLukAndPGDModule in 'SvodVedLukAndPGDModule.pas' {dm_SvodVedLukAndPG: TDataModule},
  VocCacheDModule in 'VocCacheDModule.pas' {dm_VocCache: TDataModule},
  OrderVocCacheDModule in 'OrderVocCacheDModule.pas' {dm_OrderVocCache: TDataModule},
  OrderManager in 'OrderManager.pas',
  OrderNGForm in 'OrderNGForm.pas' {frm_OrderNG},
  OrderNGDModule in 'OrderNGDModule.pas' {dm_OrderNG: TDataModule},
  ControlFrame in 'ControlFrame.pas' {frame_Control: TFrame},
  InputFrame in 'InputFrame.pas' {frame_Input: TFrame},
  BtnFrame in 'BtnFrame.pas' {frame_Btn: TFrame},
  RxDBLookupComboFrame in 'RxDBLookupComboFrame.pas' {frame_RxDBLookupCombo: TFrame},
  EditFrame in 'EditFrame.pas' {frame_Edit: TFrame},
  OutputFrame in 'OutputFrame.pas' {frame_Output: TFrame},
  LabelFrame in 'LabelFrame.pas' {frame_Label: TFrame},
  AddressFrame in 'AddressFrame.pas' {frame_Address: TFrame},
  DateEditFrame in 'DateEditFrame.pas' {frame_DateEdit: TFrame},
  TimeMaskFrame in 'TimeMaskFrame.pas' {frame_TimeMask: TFrame},
  ComboBoxFrame in 'ComboBoxFrame.pas' {frame_ComboBox: TFrame},
  RxSpinEditFrame in 'RxSpinEditFrame.pas' {frame_RxSpinEdit: TFrame},
  CheckBoxFrame in 'CheckBoxFrame.pas' {frame_CheckBox: TFrame},
  DBDateEditFrame in 'DBDateEditFrame.pas' {frame_DBDateEdit: TFrame},
  DBDateTimeEditFrame in 'DBDateTimeEditFrame.pas' {frame_DBDateTimeEdit: TFrame},
  DBTextFrame in 'DBTextFrame.pas' {frame_DBText: TFrame},
  DepChargeManager in 'DepChargeManager.pas',
  DepChargeForm in 'DepChargeForm.pas' {frm_DepCharge},
  VocAbonentsForm in 'VocAbonentsForm.pas' {frm_VocAbonents},
  ver in 'ver.pas',
  DepChargeBaseFrame in 'DepChargeBaseFrame.pas' {frame_DepChargeBase: TFrame},
  DepWorksFrame in 'DepWorksFrame.pas' {frame_DepWorks: TFrame},
  WorksVocCacheDModule in 'WorksVocCacheDModule.pas' {dm_WorksVocCache: TDataModule},
  BaseEditDModule in 'BaseEditDModule.pas' {dm_BaseEdit: TDataModule},
  BaseDepChargeDModule in 'BaseDepChargeDModule.pas' {dm_BaseDepCharge: TDataModule},
  DepMatersDModule in 'DepMatersDModule.pas' {dm_DepMaters: TDataModule},
  MatersVocCacheDModule in 'MatersVocCacheDModule.pas' {dm_MatersVocCache: TDataModule},
  DepMatersFrame in 'DepMatersFrame.pas' {frame_DepMaters: TFrame},
  DepEquipsFrame in 'DepEquipsFrame.pas' {frame_DepEquips: TFrame},
  DepEquipsDModule in 'DepEquipsDModule.pas' {dm_DepEquips: TDataModule},
  EquipsVocCacheDModule in 'EquipsVocCacheDModule.pas' {dm_EquipsVocCache: TDataModule},
  DepWorkersForm in 'DepWorkersForm.pas',
  TeamFrame in 'TeamFrame.pas' {frame_Team: TFrame},
  VocWorkersForm in 'VocWorkersForm.pas' {frm_VocWorkers},
  VocTeamsForm in 'VocTeamsForm.pas' {frm_VocTeams},
  VocWorksForm in 'VocWorksForm.pas' {frm_VocWorks},
  AvarOnMapReport in 'AvarOnMapReport.pas',
  AvarOnMapReportDModule in 'AvarOnMapReportDModule.pas' {dm_AvarOnMapReport: TDataModule},
  BoltManager in 'BoltManager.pas',
  BoltsNGForm in 'BoltsNGForm.pas' {frm_BoltsNG},
  BoltsDModule in 'BoltsDModule.pas' {dm_Bolts: TDataModule},
  AddressDModule in 'AddressDModule.pas' {dm_Address: TDataModule},
  BoltsVocCacheDModule in 'BoltsVocCacheDModule.pas' {dm_BoltsVocCache: TDataModule},
  GridFormManager in 'GridFormManager.pas',
  GridEditForm in 'GridEditForm.pas' {frm_GridEdit},
  GridEditDModule in 'GridEditDModule.pas' {dm_GridEdit: TDataModule},
  SelectItemManager in 'SelectItemManager.pas',
  OptNeedAsfaltForm in 'OptNeedAsfaltForm.pas' {frm_OptNeedAsfalt},
  RepNeedAsfaltDModule in 'RepNeedAsfaltDModule.pas' {dm_RepNeedAsfalt: TDataModule},
  SelDatePeriodFrame in 'SelDatePeriodFrame.pas' {frame_SelDatePeriod: TFrame},
  SuborderManager in 'SuborderManager.pas',
  SubOrderFrame in 'SubOrderFrame.pas' {frame_SubOrder: TFrame},
  SubOrderDModule in 'SubOrderDModule.pas' {dm_SubOrder: TDataModule},
  SubOrderForm in 'SubOrderForm.pas' {frm_SubOrder},
  SubOrderGridForm in 'SubOrderGridForm.pas' {frm_SubOrderGrid},
  GlobalVocCacheDModule in 'GlobalVocCacheDModule.pas' {dm_GlobalVocCache: TDataModule},
  VocsConst in 'VocsConst.pas',
  BaseVocAttacher in 'BaseVocAttacher.pas' {dm_BaseVocAttacher: TDataModule},
  SuborderVADModule in 'SuborderVADModule.pas' {dm_SuborderVA: TDataModule},
  VocSOAbon in 'VocSOAbon.pas' {frm_VocSOAbon},
  ItemSelecter in 'ItemSelecter.pas',
  SelItemForm in 'SelItemForm.pas' {frm_SelItem},
  VocItemSelBaseFrame in 'VocItemSelBaseFrame.pas' {frame_VocItemSelBase: TFrame},
  VocItemSelFrame in 'VocItemSelFrame.pas' {frame_VocItemSel: TFrame},
  MiniSearchOptForm in 'MiniSearchOptForm.pas' {frm_MiniSearchOpt},
  BaseFrameOptionForm in 'BaseFrameOptionForm.pas' {frm_BaseFrameOption},
  SuborderAttacher in 'SuborderAttacher.pas',
  SOAttacheDModule in 'SOAttacheDModule.pas' {dm_SOAttacher: TDataModule},
  OrderState in 'OrderState.pas',
  RepGorSESDModule in 'RepGorSESDModule.pas' {dm_RepGorSES: TDataModule},
  SOASearchResultForm in 'SOASearchResultForm.pas' {frm_SOASearchRes},
  OrderDModule in 'OrderDModule.pas' {dm_Order: TDataModule},
  VocWorkerPostForm in 'VocWorkerPostForm.pas' {frm_VocWorkerPost},
  VocWorkTimeForm in 'VocWorkTimeForm.pas' {frm_VocWorkTime},
  BWorkForm in 'BWorkForm.pas' {frm_VocBWork},
  WorkManager in 'WorkManager.pas',
  WorkDModule in 'WorkDModule.pas' {dm_Work: TDataModule},
  WorkVocAttcherDModule in 'WorkVocAttcherDModule.pas' {dm_WorkVocAttacher: TDataModule},
  WorkForm in 'WorkForm.pas' {frm_Work},
  BWorkChangeForm in 'BWorkChangeForm.pas' {frm_BWorkChange},
  BWorkInsertForm in 'BWorkInsertForm.pas' {frm_BWorkInsert},
  BWorkEditForm in 'BWorkEditForm.pas' {frm_BWorkEdit},
  BWorkDelForm in 'BWorkDelForm.pas' {frm_BWorkDel},
  EditWorkForm in 'EditWorkForm.pas' {frm_EditWork},
  FastAddWorkForm in 'FastAddWorkForm.pas' {frm_FastAddWork},
  EditMaterForm in 'EditMaterForm.pas' {frm_EditMater},
  VocBWorkAddMaterForm in 'VocBWorkAddMaterForm.pas' {frm_VocBWorkAddMater},
  OptTrudoZatrat in 'OptTrudoZatrat.pas' {frm_OptTrudoZatrat},
  RepTrudoZatratDModule in 'RepTrudoZatratDModule.pas' {dm_RepTrudoZatrat: TDataModule},
  VocWorkTypeForm in 'VocWorkTypeForm.pas' {frm_VocWorkType},
  RepVipolNaryadDModule in 'RepVipolNaryadDModule.pas' {dm_RepVipolNaryad: TDataModule},
  OptVipolNaryadForm in 'OptVipolNaryadForm.pas' {frm_OptVipolNaryad},
  OptNetBarForm in 'OptNetBarForm.pas' {frm_OptNetBar},
  RepNetBarDModule in 'RepNetBarDModule.pas' {dm_RepNetBar: TDataModule},
  RepPovrRegionDModule in 'RepPovrRegionDModule.pas' {dm_RepPovrRegion: TDataModule},
  VocsValueConst in 'VocsValueConst.pas',
  WorkBuffDModule in 'WorkBuffDModule.pas' {dm_WorkBuff: TDataModule},
  EditWorkBuffForm in 'EditWorkBuffForm.pas' {frm_EditWorkBuff},
  WorkBuffVocAttacherDModule in 'WorkBuffVocAttacherDModule.pas' {dm_WorkBuffVocAttacher: TDataModule},
  OptSvodExcavForm in 'OptSvodExcavForm.pas' {frm_OptSvodExcav},
  RepSvodExcavDModule in 'RepSvodExcavDModule.pas' {dm_RepSvodExcav: TDataModule},
  VocMeasurementForm in 'VocMeasurementForm.pas' {frm_VocMeasurement},
  NGDepManager in 'NGDepManager.pas',
  NGDepDModule in 'NGDepDModule.pas' {dm_NGDep: TDataModule},
  DepFrame in 'DepFrame.pas' {frame_Dep: TFrame},
  DepCDPForm in 'DepCDPForm.pas' {frm_DepCDP},
  DepREGForm in 'DepREGForm.pas' {frm_DepREG},
  DepBuffDModule in 'DepBuffDModule.pas' {dm_DepBuff: TDataModule},
  BaseBuffDModule in 'BaseBuffDModule.pas' {dm_BaseBuff: TDataModule},
  TrudoZatratDModule in 'TrudoZatratDModule.pas' {dm_TrudoZatrat: TDataModule},
  NumSOBuffDModule in 'NumSOBuffDModule.pas' {dm_NumSOBuff: TDataModule},
  NumSOForm in 'NumSOForm.pas' {frm_NumSO},
  EditWorkVocDM in 'EditWorkVocDM.pas' {dm_EditWorkVoc: TDataModule},
  DisconnectionsDModule in 'DisconnectionsDModule.pas' {DM_Disconnect: TDataModule},
  ClorDModule in 'ClorDModule.pas' {dm_Clor: TDataModule},
  Svodka062DModule in 'Svodka062DModule.pas' {dm_Svodka062: TDataModule},
  OptSvodka062Form in 'OptSvodka062Form.pas' {frm_OptSvodka062},
  MemTableFiller in 'MemTableFiller.pas',
  MemTableFillerDM in 'MemTableFillerDM.pas' {dm_MemTableFiller: TDataModule},
  SelDateTimePeriodFrame in 'SelDateTimePeriodFrame.pas' {frame_SelDateTimePeriod: TFrame},
  RepBlag2DModule in 'RepBlag2DModule.pas' {dm_RepBlag2: TDataModule},
  OptBlag2Form in 'OptBlag2Form.pas' {frm_OptBlag2},
  NewDisconnections in 'NewDisconnections.pas' {frm_DisconNew},
  PeriodRegSelCBForm in 'PeriodRegSelCBForm.pas' {frm_PeriodRegSelCB},
  VocAsfCompanyForm in 'VocAsfCompanyForm.pas' {frm_VocAsfCompany},
  RepPlanDepDModule in 'RepPlanDepDModule.pas' {dm_PlanDep: TDataModule},
  UseEquipDModule in 'UseEquipDModule.pas' {dm_UseEquip: TDataModule},
  AvarSitDModule in 'AvarSitDModule.pas' {dm_AvarSit: TDataModule},
  DisconKPVoda in 'DisconKPVoda.pas' {dm_DisconKPVoda: TDataModule},
  DateSelCBForm in 'DateSelCBForm.pas' {frm_DateSelCB},
  Search1562Form in 'Search1562Form.pas' {frm_Search1562},
  Search1562DModule in 'Search1562DModule.pas' {dm_Search1562: TDataModule},
  Search1562ResultForm in 'Search1562ResultForm.pas' {frm_Search1562Result},
  Search1562andOrdersResultForm in 'Search1562andOrdersResultForm.pas' {frm_Search1562andOrdersResult},
  OrderNG1562DModule in 'OrderNG1562DModule.pas' {dm_OrderNG1562: TDataModule},
  Spisok1562_FrameUnit in 'Spisok1562_FrameUnit.pas' {Spisok1562_Frame: TFrame},
  BlagPodrDModule in 'BlagPodrDModule.pas' {dm_BlagPodr: TDataModule},
  NaledUnit in 'NaledUnit.pas' {frm_Naled},
  NaledRepDModule in 'NaledRepDModule.pas' {dm_NaledRep: TDataModule},
  dm_AVRDisconnUnit in 'dm_AVRDisconnUnit.pas' {dm_AVRDisconn: TDataModule},
  DisconAppUnit in 'DisconAppUnit.pas' {AVRDisconnResultForm},
  dm_ShebenDModuleUnit in 'dm_ShebenDModuleUnit.pas' {dm_ShebenDModule: TDataModule},
  Order1562Manager in 'Order1562Manager.pas',
  Order1562Form in 'Order1562Form.pas' {frm_Order1562},
  OrderNG1562Form in 'OrderNG1562Form.pas' {frm_OrderNG1562},
  RepBlag3DModule in 'RepBlag3DModule.pas' {dm_RepBlag3: TDataModule},
  NODSBezVodyDModule in 'NODSBezVodyDModule.pas' {dm_NODSBezVody: TDataModule},
  RepRazrtDepDModule in 'RepRazrtDepDModule.pas' {dm_RazrtDep: TDataModule},
  SysInfo in 'SysInfo.pas',
  Options_1562 in 'Options_1562.pas' {frm_options1562},
  OrderForm_vds in 'from_VDS\OrderForm_vds.pas' {frm_Order_vds},
  DisconForm_vds in 'from_VDS\DisconForm_vds.pas' {frm_Discon},
  DeparturesForm_vds in 'from_VDS\DeparturesForm_vds.pas' {frm_Departures},
  BaseGridFrame_vds in 'from_VDS\BaseGridFrame_vds.pas' {frame_BaseGrid_vds: TFrame},
  WorkAndMaterBaseGrid_vds in 'from_VDS\WorkAndMaterBaseGrid_vds.pas' {frame_WorkAndMaterBaseGrid_vds: TFrame},
  EquipGridFrame_vds in 'from_VDS\EquipGridFrame_vds.pas' {frame_EquipGrid_vds: TFrame},
  MaterGridFrame_vds in 'from_VDS\MaterGridFrame_vds.pas' {frame_MaterGrid_vds: TFrame},
  WorkGridFrame_vds in 'from_VDS\WorkGridFrame_vds.pas' {frame_WorkGrid_vds: TFrame},
  WorkAndMaterForm_vds in 'from_VDS\WorkAndMaterForm_vds.pas' {frm_WorkAndMater},
  NGReports_vds in 'from_VDS\NGReports_vds.pas',
  NGReportManager_vds in 'from_VDS\NGReportManager_vds.pas',
  UniversalSearch2DModule_vds in 'from_VDS\UniversalSearch2DModule_vds.pas' {dm_UniversalSearch2_vds: TDataModule},
  UniversalSearchForm_vds in 'from_VDS\UniversalSearchForm_vds.pas' {frm_UniversalSearch_vds},
  BeforUnSearch in 'from_VDS\BeforUnSearch.pas' {for_univ_serch},
  SerchForOthersDModule in 'SerchForOthersDModule.pas' {dm_serchforothers: TDataModule},
  SelRegionFrame in 'from_VDS\SelRegionFrame.pas' {frame_SelRegion: TFrame},
  OptSvodVedForm_vds in 'from_VDS\OptSvodVedForm_vds.pas' {frm_OptSvodVed_vds},
  ResSvodVedForm_vds_new in 'from_VDS\ResSvodVedForm_vds_new.pas' {frm_ResSvodVed_vds_new},
  RepSvodVedDModule_vds in 'from_VDS\RepSvodVedDModule_vds.pas' {dm_RepSvodVed_vds: TDataModule},
  SnapShotManagerDModule_vds in 'from_VDS\SnapShotManagerDModule_vds.pas' {dm_SnapShotManager: TDataModule},
  OptSvodVedFormPer_vds in 'from_VDS\OptSvodVedFormPer_vds.pas' {frm_OptSvodVedPer_vds},
  RepSvodVedDModulePer_vds in 'from_VDS\RepSvodVedDModulePer_vds.pas' {dm_RepSvodVedPer_vds: TDataModule},
  OptRepDiscon_vds in 'from_VDS\OptRepDiscon_vds.pas' {frm_OptRepDiscon_vds},
  RepDisconDModule_vds in 'from_VDS\RepDisconDModule_vds.pas' {dm_RepDiscon_vds: TDataModule},
  PeriodRegSelCBForm_vds in 'from_VDS\PeriodRegSelCBForm_vds.pas' {frm_PeriodRegSelCB_vds},
  RepOpenOrdersDModule_vds in 'from_VDS\RepOpenOrdersDModule_vds.pas' {dm_RepOpenOrders_vds: TDataModule},
  RepClosedOrdersDModule_vds in 'from_VDS\RepClosedOrdersDModule_vds.pas' {dm_RepClosedOrders_vds: TDataModule},
  SvodkaGekDModule in 'from_VDS\SvodkaGekDModule.pas' {dm_SvodkaGek_vds: TDataModule},
  frm_OptionSvodGekUnit in 'from_VDS\frm_OptionSvodGekUnit.pas' {frm_OptionSvodGek},
  ActExeWorksDModule_vds in 'from_VDS\ActExeWorksDModule_vds.pas' {dm_ActExeWorks_vds: TDataModule},
  RepCurrentRayonDModule_vds in 'from_VDS\RepCurrentRayonDModule_vds.pas' {dm_RepCurrentRayon_vds: TDataModule},
  frm_OptRegSingleUnit_vds in 'from_VDS\frm_OptRegSingleUnit_vds.pas' {frm_OptRegSingle_vds},
  VedUsedMatersDModule_vds in 'from_VDS\VedUsedMatersDModule_vds.pas' {dm_VedUsedMaters_vds: TDataModule},
  CalcMaterCostDModule_vds in 'from_VDS\CalcMaterCostDModule_vds.pas' {dm_CalcMaterCost_vds: TDataModule},
  ReportManager_vds in 'from_VDS\ReportManager_vds.pas' {DM_ReportManager_vds: TDataModule},
  AVR_Report_vds in 'from_VDS\AVR_Report_vds.pas',
  Seachfor1562DModule in 'Seachfor1562DModule.pas' {dm_Seachfor1562: TDataModule},
  OptInfBlag in 'OptInfBlag.pas' {frm_InfBlag},
  RepInfBlagDModule in 'RepInfBlagDModule.pas' {dm_NGRepInfBlag: TDataModule},
  Zayv1562Manager in 'Zayv1562Manager.pas',
  workSQL in 'workSQL.pas' {dm_workSQL: TDataModule},
  CanselForm in 'CanselForm.pas' {frm_cansel1562},
  RepObrZas in 'RepObrZas.pas' {dm_RepObrZas: TDataModule},
  OptObrZas in 'OptObrZas.pas' {frm_OptObrZas},
  QCanselForm in 'QCanselForm.pas' {frm_QCansel},
  ResSvodVedForm_vds in 'from_VDS\ResSvodVedForm_vds.pas' {frm_ResSvodVed_vds},
  SaveSTDISP in 'SaveSTDISP.pas',
  RepSvodVedDModule_vds_new in 'from_VDS\RepSvodVedDModule_vds_new.pas' {dm_RepSvodVed_vds_new: TDataModule},
  OptSvodVedForm_vds_2 in 'from_VDS\OptSvodVedForm_vds_2.pas' {frm_svod_ved_vds_2},
  OptRSvodVed in 'OptRSvodVed.pas' {frm_OptRSvod},
  DModuleRSvodved in 'DModuleRSvodved.pas' {dm_RSvodved: TDataModule},
  DModuleSBlagRazr in 'DModuleSBlagRazr.pas' {dm_SBlagRazr: TDataModule},
  OptBlagRazr in 'OptBlagRazr.pas' {frm_OptBlagRazr},
  RepSvodPer_vdsmewDmodule in 'from_VDS\RepSvodPer_vdsmewDmodule.pas' {dm_RepSvodVed_vds_new_per: TDataModule},
  BaseBefor in 'BaseBefor.pas',
  save_Rasr in 'save_Rasr.pas',
  OneDayManager in 'OneDayManager.pas',
  OrderVdsDModule in 'from_VDS\OrderVdsDModule.pas' {dm_order_vds: TDataModule},
  save_ost1562 in 'save_ost1562.pas',
  GetOst1562_3 in 'GetOst1562_3.pas' {dm_GetOst1562: TDataModule},
  DepEquipPlanFrame in 'DepEquipPlanFrame.pas' {frame_DepEqipPlanChange: TFrame},
  DepEquipPlanForm in 'DepEquipPlanForm.pas' {frm_DepEqiupPlan},
  DepEquipPlanDmodule in 'DepEquipPlanDmodule.pas' {dm_DepPlanEqChange: TDataModule},
  DepPlanChangManager in 'DepPlanChangManager.pas',
  FormDepPlanWorMat in 'FormDepPlanWorMat.pas' {frm_DepPlanWorkMat},
  DepPlanWorMatDModule in 'DepPlanWorMatDModule.pas' {dm_DepPlanWorMat: TDataModule},
  VA_PlanWorks in 'VA_PlanWorks.pas' {dm_DepPlanWMVA: TDataModule},
  DepPlanWorkManager in 'DepPlanWorkManager.pas',
  AddWorkForm in 'AddWorkForm.pas' {frm_AddWork},
  STexnikDmodule in 'STexnikDmodule.pas' {dm_STexn: TDataModule},
  OptSTexnForm in 'OptSTexnForm.pas' {frm_SOptTexn},
  PlnanWorkVdsDModule in 'PlnanWorkVdsDModule.pas' {dm_PlanWorkVds: TDataModule},
  Closed1562Manager in 'Reports\Closed1562Manager.pas',
  ViewSent1562Form in 'ViewSent1562Form.pas' {frm_ViewClosed1562},
  VeiwSent1562DModule in 'VeiwSent1562DModule.pas' {dm_Closed1562View: TDataModule},
  OptPlanWorkForm in 'OptPlanWorkForm.pas' {frm_OptPlanWork},
  SPlanWorkDModule in 'SPlanWorkDModule.pas' {dm_SPlanWork: TDataModule},
  AdresDepNS in 'AdresDepNS.pas' {frm_AdresDep},
  RepBlagItogDM in 'RepBlagItogDM.pas' {dm_RepBlagItog: TDataModule},
  OptBlagItogForm in 'OptBlagItogForm.pas' {frm_OptBlagItog},
  SvPoZayvkamDModule in 'SvPoZayvkamDModule.pas' {dm_SvPoZayvkam: TDataModule},
  OptSvPoZayvkamForm in 'OptSvPoZayvkamForm.pas' {frm_OptSvPoZayvkam},
  REpBlag4DModule in 'REpBlag4DModule.pas' {dm_RepBlag4: TDataModule},
  WorksRegionForm in 'from_VDS\WorksRegionForm.pas' {frm_WorksRegions},
  WorksRegionDModule in 'from_VDS\WorksRegionDModule.pas' {dm_WorkRegion: TDataModule},
  ngreportsvdsns in 'ngreportsvdsns.pas',
  FloodingEditDModule in 'FloodingEditDModule.pas' {dm_Flooding: TDataModule},
  FloodingEditForm in 'FloodingEditForm.pas' {frm_Flooding},
  OptPlanDepForm in 'OptPlanDepForm.pas' {frm_OptPlanDep},
  OptAvrDiscon in 'OptAvrDiscon.pas' {frm_OptAvrDiscon},
  RepGreenSpringDModule in 'RepGreenSpringDModule.pas' {dm_RepGreenSpring: TDataModule},
  GreenSpringGetDate in 'GreenSpringGetDate.pas' {dm_GreenSpringGetDate: TDataModule},
  OptGreenSpring in 'OptGreenSpring.pas' {frm_OptGreenSpring},
  NewDisconnections2 in 'NewDisconnections2.pas' {frm_DisconNew2},
  ClientImage in 'ClientImage.pas' {dm_ClientImage: TDataModule},
  AvrPictersDModule in 'AvrPictersDModule.pas' {dm_avrpicter: TDataModule},
  picterframe in 'picterframe.pas' {Frame_picters: TFrame},
  Image_main in 'Image_main.pas' {frm_picters},
  DisconSite in 'DisconSite.pas' {dm_AVRDisconnSite: TDataModule},
  ResultDisconSite in 'Reports\ResultDisconSite.pas' {DisconnSiteResult},
  OptRSvodVed_ns in 'OptRSvodVed_ns.pas' {frm_OptRSvod_ns},
  OptRSvodVed_vds in 'OptRSvodVed_vds.pas' {frm_OptRSvod_vds},
  VedNotCloseOrderDModule_vds in 'VedNotCloseOrderDModule_vds.pas' {dm_VedNotCloseOrder_vds: TDataModule},
  Report1321 in 'FrmReposrts\Report1321.pas' {dm_Report1321: TDataModule},
  Report1321Opt in 'FrmReposrts\Report1321Opt.pas' {frm_optReport1321},
  TrnaferFromAdoQToRmem in 'TrnaferFromAdoQToRmem.pas',
  ExcavOrderTableDModule in 'ExcavOrderTableDModule.pas' {dm_ExcavOrderTable: TDataModule},
  ngreports2 in 'ngreports2.pas',
  ApplicationForSbitDmodule in 'ApplicationForSbitDmodule.pas' {dm_ApplicationForSbit: TDataModule},
  ApplicationForSbitOptForm in 'ApplicationForSbitOptForm.pas' {frm_OptApplicationForSbit},
  DamageBlagObjectDModule in 'DamageBlagObjectDModule.pas' {Tdm_DamageBlagObject: TDataModule},
  OptGetToDoNar in 'from_VDS\OptGetToDoNar.pas' {frm_OptGetToDoNar},
  GetToDoNarDMobule in 'from_VDS\GetToDoNarDMobule.pas' {dm_GetToDoNar: TDataModule},
  ReportAll1Dmodule in 'ReportAll1Dmodule.pas' {dm_ReportAll1: TDataModule},
  ZvClosedOrderDModule in 'ZvClosedOrderDModule.pas' {dm_ZvClosedOrder: TDataModule},
  OptZvCloseOrderForm in 'OptZvCloseOrderForm.pas' {frm_OptZvCloseOrder};

{$R *.RES}

begin
  //MemChk;

  if IsRun then
  begin
    MessageBox(0, 'Программа "Диспетчер АВР" уже запущена', 'Ошибка', MB_OK or MB_ICONERROR);
    halt; //завершить программу не создавая ничего.
  end;

  Application.Initialize();
  frm_Zastavka:=Tfrm_Zastavka.Create(Application);
  frm_Zastavka.Show;
  frm_Zastavka.Update;
  Application.Title := 'АВР ВОДОСЕТЬ';
  Application.CreateForm(TDM_Main, DM_Main);
  Application.CreateForm(TDM_RightsManager, DM_RightsManager);
  Application.CreateForm(Tdm_GlobalVocCache, dm_GlobalVocCache);
  Application.CreateForm(Tfrm_Main, frm_Main);
  Application.CreateForm(Tdm_ShebenDModule, dm_ShebenDModule);
  Application.CreateForm(Tdm_Seachfor1562, dm_Seachfor1562);
  Application.CreateForm(Tdm_workSQL, dm_workSQL);
  Application.CreateForm(TTdm_DamageBlagObject, Tdm_DamageBlagObject);
  Application.CreateForm(Tfrm_OptGetToDoNar, frm_OptGetToDoNar);
  Application.CreateForm(Tdm_GetToDoNar, dm_GetToDoNar);
  Application.CreateForm(Tdm_ReportAll1, dm_ReportAll1);
  Application.CreateForm(Tdm_ZvClosedOrder, dm_ZvClosedOrder);
  Application.CreateForm(Tfrm_OptZvCloseOrder, frm_OptZvCloseOrder);
  // Application.CreateForm(Tdm_RepSvodVed_vds_new_per, dm_RepSvodVed_vds_new_per);
  //  Application.CreateForm(Tfrm_OptRSvod, frm_OptRSvod);
 // Application.CreateForm(Tdm_RSvodved, dm_RSvodved);
 // Application.CreateForm(Tdm_SBlagRazr, dm_SBlagRazr);
 // Application.CreateForm(Tfrm_OptBlagRazr, frm_OptBlagRazr);
  //Application.CreateForm(Tdm_RepSvodVed_vds_new, dm_RepSvodVed_vds_new);
  //Application.CreateForm(Tfrm_cansel1562, frm_cansel1562);
  //  Application.CreateForm(Tfrm_WorkAndMater, frm_WorkAndMater);
//  Application.CreateForm(Tfrm_UniversalSearch_vds, frm_UniversalSearch_vds);
//  Application.CreateForm(Tfor_univ_serch, for_univ_serch);
  // Application.CreateForm(Tfrm_options1562, frm_options1562);
  //  Application.CreateForm(TEditDisconnectionsForm, EditDisconnectionsForm);
//  Application.CreateForm(Tfrm_DisconNew, frm_DisconNew);
//  Application.CreateForm(Tfrm_PeriodRegSelCB, frm_PeriodRegSelCB);
  //  Application.CreateForm(Tfrm_DateSelCB, frm_DateSelCB);
  //  Application.CreateForm(Tdm_DisconKPVoda, dm_DisconKPVoda);
  //  Application.CreateForm(Tdm_AvarSit, dm_AvarSit);
  //  Application.CreateForm(Tdm_PlanDep, dm_PlanDep);
//  Application.CreateForm(Tdm_UseEquip, dm_UseEquip);
  //  Application.CreateForm(TDM_Disconnect, DM_Disconnect);
  frm_Zastavka.Hide;
  frm_Zastavka.Free;
  Application.Run;
end.

