unit ExcSpreadSheet;

interface

{$I !TEST_DEFINE.inc}

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, Grids, Aligrid, DB, ExtCtrls, StdCtrls, Buttons,ComObj,
  RxStrUtils, Math, DModule, IBCustomDataSet, ProgressForm,
  IBDatabase;

const
  raonord:array [1..9] of short=(1,2,8,3,5,4,7,6,9);

type
  TfmExcSprSheet = class(TForm)
    StringAlignGrid1: TStringAlignGrid;
    Panel1: TPanel;
    BitBtn1: TBitBtn;
    BitBtn2: TBitBtn;
    dset_tmp: TIBDataSet;
    pind_Proc: TProgressIndicator;
    tran_tmp: TIBTransaction;
    procedure BitBtn2Click(Sender: TObject);
    procedure ExcelButtonClick(Sender: TObject);
    procedure FormClose(Sender: TObject; var Action: TCloseAction);
    constructor CreateParam(AOwner:TComponent; DateBeg:TDateTime; DateEnd:TDateTime; CB: boolean);
    procedure FormCreate(Sender: TObject);
  private
    { Private declarations }
    sDate, fn:string;
    
    DtBeg,DtEnd:TDateTime;
    procedure FillCol(Col:integer;ds:TIBDataSet;idname:string='id';valuename:string='val');
    procedure FillGrid;
  public
    { Public declarations }
  end;

implementation

{$R *.dfm}

uses ApplicationSettings {$ifdef test},TestUnit{$endif};

procedure TfmExcSprSheet.FillCol(Col:integer;ds:TIBDataSet;idname:string='id';valuename:string='val');
var
  s:integer;
begin
  {$ifdef test}
  TEST_SaveStrings2File(ds.SelectSQL, IntToStr(Col)+ClassName+'.'+ds.Name);
  {$endif}
  s:=0;
  ds.Open;
  ds.First;
  while not ds.Eof do
  begin
    StringAlignGrid1.Cells[Col,raonord[ds.FieldByName(idname).AsInteger]]:=ds.FieldByName(valuename).AsString;
    s:=s+ds.FieldByName(valuename).AsInteger;
    ds.next;
  end;
  ds.close;
  StringAlignGrid1.Cells[Col,11]:=IntToStr(s);
end;

procedure TfmExcSprSheet.BitBtn2Click(Sender: TObject);
begin
  close;
end;

procedure TfmExcSprSheet.ExcelButtonClick(Sender: TObject);
var
  Sag:TStringAlignGrid;
  TempVar:Variant;
  ii,jj:integer;
  XL:Variant;
  TempWinCont:TComponent;
  IntCell:integer;
begin
  if fn<>'' then
    DeleteFile(fn);

    try
      try
        XL := GetActiveOleObject('Excel.Application');
      except
        XL := CreateOleObject('Excel.Application');
      end;
    except
      raise Exception.Create('=х ьюує чряєёЄшЄ№ Excel');
    end;

  XL.Workbooks.Open(AppSettings.Reports_Path+ '\ExcSpreadSheet_template.xls');

    XL.ActiveWorkbook.Author := 'Generated by  Main Dispatcher program';
    Sag:=StringAlignGrid1;
    TempVar := VarArrayCreate([0, Sag.RowCount - 2, //ъюы-тю ёЄЁюъ
        0, Sag.ColCount - 2], // ъюы-тю ёЄюысЎют
        varOleStr);

    For ii:=Sag.FixedRows to Sag.RowCount-3 do
      For jj:=Sag.FixedCols to Sag.ColCount-1 do
        begin
          TempVar[ii-Sag.FixedRows, jj-Sag.FixedCols] := Trim(Sag.Cells[jj,ii]);
        end;

      For jj:=Sag.FixedCols to Sag.ColCount-1 do
        begin
          TempVar[Sag.RowCount-3, jj-Sag.FixedCols] := Trim(Sag.Cells[jj,Sag.RowCount-1]);
        end;

    XL.Range[XL.Cells[7, 2],
      XL.Cells[Sag.RowCount+4,
      Sag.ColCount]].Value := TempVar;

    XL.Cells[1, 1]:='Сводная ведомость по разрытиям при ликвидации повреждений на водопроводных сетях г. Харькова за период с '+DateToStr(DtBeg)+' по '+DateToStr(DtEnd);

  fn:=ExtractFileDir(Application.ExeName)+'\xar'+DelSpace(DelChars(DelChars(DateTimeToStr(Now),'.'),':'))+'.xls';
  XL.ActiveWorkbook.SaveAs(fn);
  XL.Visible := True;
end;


procedure TfmExcSprSheet.FormClose(Sender: TObject;
  var Action: TCloseAction);
begin
  if FileExists(fn) then
    DeleteFile(fn);
  Action:=caFree;
end;

constructor TfmExcSprSheet.CreateParam(AOwner:TComponent; DateBeg:TDateTime; DateEnd:TDateTime ; CB: boolean);
begin
  DtBeg:=Max(DateBeg,StrToDate('01.01.2004'));
  DtEnd:=Min(DateEnd,Now);
  if not CB then sDate := ' and (o.DateComing>='''+DateToStr(DtBeg)+''')' else sDate := '';
  inherited Create(AOwner)
end;

procedure TfmExcSprSheet.FillGrid;
begin
 fn:='';
 StringAlignGrid1.FixedColFont[0].Size:=10;
 StringAlignGrid1.FixedColFont[0].Style:=[fsBold];
 StringAlignGrid1.FixedRowFont[0].Size:=10;
 StringAlignGrid1.FixedRowFont[0].Style:=[fsBold];
 StringAlignGrid1.FixAlignCol[0]:=alLeft;
 Caption:='Анализ раскопок за период с '+DateToStr(DtBeg)+' по '+DateToStr(DtEnd);
 pind_Proc.Show;

 {Всего разрытий}
 (*
 qry_temp.Sql.Text:='select s.raon_cod, count(distinct narjad_nom) cc from soob_wk s, excav e '+
                  'where (s.data_soob=e.date_order) and( s.narjad_nom=e.num_order) and (s.mesto_pv_c in (1,2)) '+
                  ' and (e.action in (1,2,3,6,9)) and (s.mestnst_c in (1,2,3,5,6,7)) and (s.data_soob>='''+DateToStr(DtBeg)+''')'+
                  ' and (e.date_action<'''+DateToStr(DtEnd)+''')'+
                  ' group by s.raon_cod';
 *)
 dset_tmp.SelectSQL.Text:=' select o.fk_orders_regions reg_cod, count(distinct OrderNumber) cc'+
                          ' from orders o, excavations e'+
                          ' where (o.id=e.fk_excavations_orders) and (o.fk_orders_damageplace in (1,2))'+
                          ' and (e.fk_Excavations_Excwt in (1,2,3,6,9)) and (o.fk_orders_damagelocality in (1,2,3,5,6,7))'+
//                          ' and (o.DateComing>='''+DateToStr(DtBeg)+''')'+
                           sDate +
                          ' and (DTime>='''+DateToStr(DtBeg)+''')'+
                          ' and (DTime<'''+DateToStr(DtEnd)+''')'+
                          ' group by o.fk_orders_regions';
 FillCol(1,dset_tmp,'reg_cod','cc');
 pind_Proc.Position:=pind_Proc.Position+6;
 {/Всего разрытий}

 {Асфальт разрытий}
(*
 qry_temp.Sql.Text:='select s.raon_cod, count(distinct narjad_nom) cc from soob_wk s, excav e '+
                  'where (s.data_soob=e.date_order) and( s.narjad_nom=e.num_order) and (s.mesto_pv_c in (1,2)) '+
                  ' and (e.action in (1,2,3,6,9)) and (s.mestnst_c in (1,2,6,7)) and (s.data_soob>='''+DateToStr(DtBeg)+''')'+
                  ' and (e.date_action<'''+DateToStr(DtEnd)+''')'+
                  ' group by s.raon_cod';
*)
 dset_tmp.SelectSQL.Text:=' select o.fk_orders_regions reg_cod, count(distinct OrderNumber) cc'+
                          ' from orders o, excavations e'+
                          ' where (o.id=e.fk_excavations_orders) and (o.fk_orders_damageplace in (1,2))'+
                          ' and (e.fk_Excavations_Excwt in (1,2,3,6,9)) and (o.fk_orders_damagelocality in (1,2,6,7))'+
                        //  ' and (o.DateComing>='''+DateToStr(DtBeg)+''')'+
                         sDate +
                          ' and (DTime>='''+DateToStr(DtBeg)+''')'+
                          ' and (DTime<'''+DateToStr(DtEnd)+''')'+
                          ' group by o.fk_orders_regions';
 FillCol(2,dset_tmp,'reg_cod','cc');
 pind_Proc.Position:=pind_Proc.Position+6;
 {/Асфальт разрытий}


 {Асфальт передано в КДЭП шт}
(*
 qry_temp.Sql.Text:='select s.raon_cod, count(distinct narjad_nom) cc from soob_wk s, excav e '+
                  'where (s.data_soob=e.date_order) and( s.narjad_nom=e.num_order) and (s.mesto_pv_c in (1,2)) '+
                  ' and (e.action in (7)) and (s.mestnst_c in (1,2,6,7)) and (s.data_soob>='''+DateToStr(DtBeg)+''')'+
                  ' and (e.date_action<'''+DateToStr(DtEnd)+''')'+
                  ' group by s.raon_cod';
*)
 dset_tmp.SelectSQL.Text:=' select o.fk_orders_regions reg_cod, count(distinct OrderNumber) cc'+
                          ' from orders o, excavations e'+
                          ' where (o.id=e.fk_excavations_orders) and (o.fk_orders_damageplace in (1,2))'+
                          ' and (e.fk_Excavations_Excwt in (7)) and (o.fk_orders_damagelocality in (1,2,6,7))'+
//                          ' and (o.DateComing>='''+DateToStr(DtBeg)+''')'+
                          sDate + 
                          ' and (DTime>='''+DateToStr(DtBeg)+''')'+
                          ' and (DTime<'''+DateToStr(DtEnd)+''')'+
                          ' group by o.fk_orders_regions';
 FillCol(3,dset_tmp,'reg_cod','cc');
 pind_Proc.Position:=pind_Proc.Position+6;
 {/Асфальт передано в КДЭП шт}

 {Асфальт передано в КДЭП м2}
(*
 qry_temp.Sql.Text:='select s.raon_cod, sum(give) cc from soob_wk s, excav e '+
                  'where (s.data_soob=e.date_order) and( s.narjad_nom=e.num_order) and (s.mesto_pv_c in (1,2)) '+
                  ' and (e.action in (7)) and (s.mestnst_c in (1,2,6,7)) and (s.data_soob>='''+DateToStr(DtBeg)+''')'+
                  ' and (e.date_action<'''+DateToStr(DtEnd)+''')'+
                  ' group by s.raon_cod';
*)
 dset_tmp.SelectSQL.Text:=' select o.fk_orders_regions reg_cod, sum(e.square) cc'+
                          ' from orders o, excavations e'+
                          ' where (o.id=e.fk_excavations_orders) and (o.fk_orders_damageplace in (1,2))'+
                          ' and (e.fk_Excavations_Excwt in (7)) and (o.fk_orders_damagelocality in (1,2,6,7))'+
//                          ' and (o.DateComing>='''+DateToStr(DtBeg)+''')'+
                          sDate +
                          ' and (DTime>='''+DateToStr(DtBeg)+''')'+
                          ' and (DTime<'''+DateToStr(DtEnd)+''')'+
                          ' group by o.fk_orders_regions';
 FillCol(4,dset_tmp,'reg_cod','cc');
 pind_Proc.Position:=pind_Proc.Position+6;
 {/Асфальт передано в КДЭП м2}

 {Асфальт выполнено шт}
(*
 qry_temp.Sql.Text:='select s.raon_cod, count(distinct narjad_nom) cc from soob_wk s, excav e '+
                  'where (s.data_soob=e.date_order) and( s.narjad_nom=e.num_order) and (s.mesto_pv_c in (1,2)) '+
                  ' and (e.action in (5)) and (s.mestnst_c in (1,2,6,7)) and (s.data_soob>='''+DateToStr(DtBeg)+''')'+
                  ' and (e.date_action<'''+DateToStr(DtEnd)+''')'+
                  ' group by s.raon_cod';
*)
 dset_tmp.SelectSQL.Text:=' select o.fk_orders_regions reg_cod, count(distinct OrderNumber) cc'+
                          ' from orders o, excavations e'+
                          ' where (o.id=e.fk_excavations_orders) and (o.fk_orders_damageplace in (1,2))'+
                          ' and (e.fk_Excavations_Excwt in (5)) and (o.fk_orders_damagelocality in (1,2,6,7))'+
                          //' and (o.DateComing>='''+DateToStr(DtBeg)+''')'+
                          sDate +
                          ' and (DTime>='''+DateToStr(DtBeg)+''')'+
                          ' and (DTime<'''+DateToStr(DtEnd)+''')'+
                          ' group by o.fk_orders_regions';
 FillCol(5,dset_tmp,'reg_cod','cc');
 pind_Proc.Position:=pind_Proc.Position+6;
 {/Асфальт выполнено шт}

 {Асфальт выполнено м2}
(*
 qry_temp.Sql.Text:='select s.raon_cod, sum(give) cc from soob_wk s, excav e '+
                  'where (s.data_soob=e.date_order) and( s.narjad_nom=e.num_order) and (s.mesto_pv_c in (1,2)) '+
                  ' and (e.action in (5)) and (s.mestnst_c in (1,2,6,7)) and (s.data_soob>='''+DateToStr(DtBeg)+''')'+
                  ' and (e.date_action<'''+DateToStr(DtEnd)+''')'+
                  ' group by s.raon_cod';
*)
 dset_tmp.SelectSQL.Text:=' select o.fk_orders_regions reg_cod, sum(e.square) cc'+
                          ' from orders o, excavations e'+
                          ' where (o.id=e.fk_excavations_orders) and (o.fk_orders_damageplace in (1,2))'+
                          ' and (e.fk_Excavations_Excwt in (5)) and (o.fk_orders_damagelocality in (1,2,6,7))'+
                          //' and (o.DateComing>='''+DateToStr(DtBeg)+''')'+
                          sDate +
                          ' and (DTime>='''+DateToStr(DtBeg)+''')'+
                          ' and (DTime<'''+DateToStr(DtEnd)+''')'+
                          ' group by o.fk_orders_regions';
 FillCol(6,dset_tmp,'reg_cod','cc');
 pind_Proc.Position:=pind_Proc.Position+6;
 {/Асфальт выполнено м2}

 {Асфальт оплачено шт}
(*
 qry_temp.Sql.Text:='select s.raon_cod, count(distinct narjad_nom) cc from soob_wk s, excav e '+
                  'where (s.data_soob=e.date_order) and( s.narjad_nom=e.num_order) and (s.mesto_pv_c in (1,2)) '+
                  ' and (e.action in (8)) and (s.mestnst_c in (1,2,6,7)) and (s.data_soob>='''+DateToStr(DtBeg)+''')'+
                  ' and (e.date_action<'''+DateToStr(DtEnd)+''')'+
                  ' group by s.raon_cod';
*)
 dset_tmp.SelectSQL.Text:=' select o.fk_orders_regions reg_cod, count(distinct OrderNumber) cc'+
                          ' from orders o, excavations e'+
                          ' where (o.id=e.fk_excavations_orders) and (o.fk_orders_damageplace in (1,2))'+
                          ' and (e.fk_Excavations_Excwt in (8)) and (o.fk_orders_damagelocality in (1,2,6,7))'+
                          //' and (o.DateComing>='''+DateToStr(DtBeg)+''')'+
                          sDate +
                          ' and (DTime>='''+DateToStr(DtBeg)+''')'+
                          ' and (DTime<'''+DateToStr(DtEnd)+''')'+
                          ' group by o.fk_orders_regions';
 FillCol(7,dset_tmp,'reg_cod','cc');
 pind_Proc.Position:=pind_Proc.Position+6;
 {/Асфальт оплачено шт}

 {Асфальт оплачено  не  нулевых шт}
(*
 qry_temp.Sql.Text:='select s.raon_cod, count(distinct narjad_nom) cc from soob_wk s, excav e '+
                  'where (s.data_soob=e.date_order) and( s.narjad_nom=e.num_order) and (s.mesto_pv_c in (1,2)) '+
                  ' and (e.action in (8)) and (s.mestnst_c in (1,2,6,7)) and (s.data_soob>='''+DateToStr(DtBeg)+''')'+
                  ' and (e.date_action<'''+DateToStr(DtEnd)+''')'+' and (e.give=0) '+
                  ' group by s.raon_cod';
*)
 dset_tmp.SelectSQL.Text:=' select o.fk_orders_regions reg_cod, count(distinct OrderNumber) cc'+
                          ' from orders o, excavations e'+
                          ' where (o.id=e.fk_excavations_orders) and (o.fk_orders_damageplace in (1,2))'+
                          ' and (e.fk_Excavations_Excwt in (8)) and (o.fk_orders_damagelocality in (1,2,6,7))'+
                          //' and (o.DateComing>='''+DateToStr(DtBeg)+''')'+
                          sDate +
                          ' and (DTime>='''+DateToStr(DtBeg)+''')'+
                          ' and (DTime<'''+DateToStr(DtEnd)+''') and (e.Square=0)'+
                          ' group by o.fk_orders_regions';
 FillCol(8,dset_tmp,'reg_cod','cc');
 pind_Proc.Position:=pind_Proc.Position+1;
 {/Асфальт оплачено  не  нулевых шт}


 {Асфальт оплачено м2}
(*
 qry_temp.Sql.Text:='select s.raon_cod, sum(give) cc from soob_wk s, excav e '+
                  'where (s.data_soob=e.date_order) and( s.narjad_nom=e.num_order) and (s.mesto_pv_c in (1,2)) '+
                  ' and (e.action in (8)) and (s.mestnst_c in (1,2,6,7)) and (s.data_soob>='''+DateToStr(DtBeg)+''')'+
                  ' and (e.date_action<'''+DateToStr(DtEnd)+''')'+
                  ' group by s.raon_cod';
*)
 dset_tmp.SelectSQL.Text:=' select o.fk_orders_regions reg_cod, sum(e.square) cc'+
                          ' from orders o, excavations e'+
                          ' where (o.id=e.fk_excavations_orders) and (o.fk_orders_damageplace in (1,2))'+
                          ' and (e.fk_Excavations_Excwt in (8)) and (o.fk_orders_damagelocality in (1,2,6,7))'+
                          //' and (o.DateComing>='''+DateToStr(DtBeg)+''')'+
                          sDate +
                          ' and (DTime>='''+DateToStr(DtBeg)+''')'+
                          ' and (DTime<'''+DateToStr(DtEnd)+''')'+
                          ' group by o.fk_orders_regions';
 FillCol(9,dset_tmp,'reg_cod','cc');
 pind_Proc.Position:=pind_Proc.Position+6;
 {/Асфальт оплачено м2}

 {Асфальт не выполнено шт}
(*
 qry_temp.Sql.Text:='select s.raon_cod, count(distinct narjad_nom) cc from soob_wk s '+
                  'where (s.mesto_pv_c in (1,2)) and mestnst_c in (1,2,6,7) and (s.data_soob>='''+DateToStr(DtBeg)+''') '+
                  '  and Exists(select pole from excav e1 where e1.date_order=s.data_soob and e1.num_order=s.narjad_nom and e1.action in (1,2,3,9) and (e1.date_action<'''+DateToStr(DtEnd)+''')) '+
                  '  and not Exists(select pole from excav e1 where e1.date_order=s.data_soob and e1.num_order=s.narjad_nom and e1.action in (5)  and (e1.date_action<'''+DateToStr(DtEnd)+''')) '+
                  ' group by s.raon_cod';
*)
 dset_tmp.SelectSQL.Text:=' select o.fk_orders_regions reg_cod, count(distinct OrderNumber) cc from orders o, excavations e1'+
                          ' where (o.fk_orders_damageplace in (1,2)) and (o.fk_orders_damagelocality in (1,2,6,7))'+
                         // ' and (o.datecoming>='''+DateToStr(DtBeg)+''')'+
                          sDate +
                          ' and e1.fk_excavations_orders=o.id and e1.fk_excavations_excwt in (1,2,3,9) and (e1.DTime<'''+DateToStr(DtEnd)+''')'+
                          ' and o.id not in ('+
                          '    select e2.fk_excavations_orders'+
                          '    from excavations e2'+
                          '    where (e2.fk_excavations_excwt =5) and (e2.DTime<'''+DateToStr(DtEnd)+''')'+
                          '    )'+
                          ' group by o.fk_orders_regions';

 FillCol(11,dset_tmp,'reg_cod','cc');
 pind_Proc.Position:=pind_Proc.Position+6;
 {/Асфальт не выполнено шт}


 {Асфальт не выполнено м2}
(*
 qry_temp.Sql.Text:='select s.raon_cod, sum(give) cc from soob_wk s, excav e '+
                  'where (s.mesto_pv_c in (1,2)) and mestnst_c in (1,2,6,7) and (s.data_soob>='''+DateToStr(DtBeg)+''') '+
                  '  and (e.date_order=s.data_soob) and (e.num_order=s.narjad_nom) and (e.action=7) '+
                  '  and Exists(select pole from excav e1 where e1.date_order=s.data_soob and e1.num_order=s.narjad_nom and e1.action in (1,2,3,9) and (e1.date_action<'''+DateToStr(DtEnd)+'''))'+
                  '  and not Exists(select pole from excav e1 where e1.date_order=s.data_soob and e1.num_order=s.narjad_nom and e1.action in (5) and (e1.date_action<'''+DateToStr(DtEnd)+''')) '+
                  ' and (e.date_action<'''+DateToStr(DtEnd)+''')'+
                  ' group by s.raon_cod';
*)
 dset_tmp.SelectSQL.Text:=' select o.fk_orders_regions reg_cod, sum(e1.square) cc from orders o, excavations e1'+
                          ' where (o.fk_orders_damageplace in (1,2)) and (o.fk_orders_damagelocality in (1,2,6,7))'+
                          //' and (o.datecoming>='''+DateToStr(DtBeg)+''')'+
                          sDate +
                          ' and (e1.fk_excavations_orders=o.id) and (e1.fk_excavations_excwt=7)'+
                          ' and (e1.DTime<'''+DateToStr(DtEnd)+''')'+
                          ' and (e1.DTime>='''+DateToStr(DtBeg)+''')'+
                          ' and o.id in ('+
                          '    select e2.fk_excavations_orders'+
                          '    from excavations e2'+
                          '    where (e2.fk_excavations_excwt in (1,2,3,9)) and (e2.DTime<'''+DateToStr(DtEnd)+''')'+
                          '    and (e2.DTime>='''+DateToStr(DtBeg)+''')'+
                          '    )'+
                          ' and o.id not in ('+
                          '    select e2.fk_excavations_orders'+
                          '    from excavations e2'+
                          '    where (e2.fk_excavations_excwt=5) and (cast(e2.DTime as Date)<'''+DateToStr(DtEnd)+''')'+
                          '    and (e2.DTime>='''+DateToStr(DtBeg)+''')'+
                          '    )'+
                          ' group by o.fk_orders_regions';

 FillCol(12,dset_tmp,'reg_cod','cc');
 pind_Proc.Position:=pind_Proc.Position+6;
 {/Асфальт не выполнено м2}

 {Грунт разрытий}
(*
 qry_temp.Sql.Text:='select s.raon_cod, count(distinct narjad_nom) cc from soob_wk s, excav e '+
                  'where (s.data_soob=e.date_order) and( s.narjad_nom=e.num_order) and (s.mesto_pv_c in (1,2)) '+
                  ' and (e.action in (1,2,3,6)) and (s.mestnst_c in (5)) and (s.data_soob>='''+DateToStr(DtBeg)+''')'+
                  ' and (e.date_action<'''+DateToStr(DtEnd)+''')'+
                  ' group by s.raon_cod';
*)
 dset_tmp.SelectSQL.Text:=' select o.fk_orders_regions reg_cod, count(distinct OrderNumber) cc'+
                          ' from orders o, excavations e'+
                          ' where (o.id=e.fk_excavations_orders) and (o.fk_orders_damageplace in (1,2))'+
                          ' and (e.fk_Excavations_Excwt in (1,2,3,6)) and (o.fk_orders_damagelocality in (5))'+
                         // ' and (o.DateComing>='''+DateToStr(DtBeg)+''')'+
                          sDate +
                          ' and (DTime>='''+DateToStr(DtBeg)+''')'+
                          ' and (DTime<'''+DateToStr(DtEnd)+''')'+
                          ' group by o.fk_orders_regions';
 FillCol(14,dset_tmp,'reg_cod','cc');
 pind_Proc.Position:=pind_Proc.Position+6;
 {/Грунт разрытий}


 {Грунт разрытий востанн}
(*
 qry_temp.Sql.Text:='select s.raon_cod, count(distinct narjad_nom) cc from soob_wk s, excav e '+
                  'where (s.data_soob=e.date_order) and( s.narjad_nom=e.num_order) and (s.mesto_pv_c in (1,2)) '+
                  ' and (e.action in (6)) and (s.mestnst_c in (5)) and (s.data_soob>='''+DateToStr(DtBeg)+''')'+
                  ' and (e.date_action<'''+DateToStr(DtEnd)+''')'+
                  ' group by s.raon_cod';
*)
 dset_tmp.SelectSQL.Text:=' select o.fk_orders_regions reg_cod, count(distinct OrderNumber) cc'+
                          ' from orders o, excavations e'+
                          ' where (o.id=e.fk_excavations_orders) and (o.fk_orders_damageplace in (1,2))'+
                          ' and (e.fk_Excavations_Excwt in (6)) and (o.fk_orders_damagelocality in (5))'+
                          //' and (o.DateComing>='''+DateToStr(DtBeg)+''')'+
                          sDate +
                          ' and (DTime>='''+DateToStr(DtBeg)+''')'+
                          ' and (DTime<'''+DateToStr(DtEnd)+''')'+
                          ' group by o.fk_orders_regions';
 FillCol(15,dset_tmp,'reg_cod','cc');
 pind_Proc.Position:=pind_Proc.Position+6;
 {/Грунт разрытий востанн}


 {Грунт разрытий не восстанов}
(*
 qry_temp.Sql.Text:='select s.raon_cod, count(distinct narjad_nom) cc from soob_wk s '+
                  'where (s.mesto_pv_c in (1,2)) and mestnst_c in (5) and (s.data_soob>='''+DateToStr(DtBeg)+''') '+
                  '  and Exists(select pole from excav e1 where e1.date_order=s.data_soob and e1.num_order=s.narjad_nom and e1.action in (1,2,3,9) and (e1.date_action<'''+DateToStr(DtEnd)+''')) '+
                  '  and not Exists(select pole from excav e1 where e1.date_order=s.data_soob and e1.num_order=s.narjad_nom and e1.action in (6) and (e1.date_action<'''+DateToStr(DtEnd)+''')) '+
                  ' group by s.raon_cod';
*)
 dset_tmp.SelectSQL.Text:=' select o.fk_orders_regions reg_cod, count(distinct OrderNumber) cc from orders o, excavations e1'+
                          ' where (o.fk_orders_damageplace in (1,2)) and (o.fk_orders_damagelocality in (5))'+
                          //' and (o.datecoming>='''+DateToStr(DtBeg)+''')'+
                          sDate +
                          ' and e1.fk_excavations_orders=o.id and e1.fk_excavations_excwt in (1,2,3,9) and (e1.DTime<'''+DateToStr(DtEnd)+''')'+
                          ' and (e1.DTime>='''+DateToStr(DtBeg)+''')'+
                          ' and o.id not in ('+
                          '    select e2.fk_excavations_orders'+
                          '    from excavations e2'+
                          '    where (e2.fk_excavations_excwt =6) and (e2.DTime<'''+DateToStr(DtEnd)+''')'+
                          '    and (e2.DTime>='''+DateToStr(DtBeg)+''')'+
                          '    )'+
                          ' group by o.fk_orders_regions';

 FillCol(16,dset_tmp,'reg_cod','cc');
 pind_Proc.Position:=pind_Proc.Position+6;
 {/Грунт разрытий не восстанов}

 {Зеленая зона разрытий}
(*
 qry_temp.Sql.Text:='select s.raon_cod, count(distinct narjad_nom) cc from soob_wk s, excav e '+
                  'where (s.data_soob=e.date_order) and( s.narjad_nom=e.num_order) and (s.mesto_pv_c in (1,2)) '+
                  ' and (e.action in (1,2,3,6)) and (s.mestnst_c in (3)) and (s.data_soob>='''+DateToStr(DtBeg)+''')'+
                  ' and (e.date_action<'''+DateToStr(DtEnd)+''')'+
                  ' group by s.raon_cod';
*)
 dset_tmp.SelectSQL.Text:=' select o.fk_orders_regions reg_cod, count(distinct OrderNumber) cc'+
                          ' from orders o, excavations e'+
                          ' where (o.id=e.fk_excavations_orders) and (o.fk_orders_damageplace in (1,2))'+
                          ' and (e.fk_Excavations_Excwt in (1,2,3,6)) and (o.fk_orders_damagelocality in (3))'+
                         // ' and (o.DateComing>='''+DateToStr(DtBeg)+''')'+
                          sDate +
                          ' and (DTime>='''+DateToStr(DtBeg)+''')'+
                          ' and (DTime<'''+DateToStr(DtEnd)+''')'+
                          ' group by o.fk_orders_regions';
 FillCol(17,dset_tmp,'reg_cod','cc');
 pind_Proc.Position:=pind_Proc.Position+6;
 {/Зеленая зона разрытий}

 {Зеленая зона востановлено}
(*
 qry_temp.Sql.Text:='select s.raon_cod, count(distinct narjad_nom) cc from soob_wk s, excav e '+
                  'where (s.data_soob=e.date_order) and( s.narjad_nom=e.num_order) and (s.mesto_pv_c in (1,2)) '+
                  ' and (e.action in (6)) and (s.mestnst_c in (3)) and (s.data_soob>='''+DateToStr(DtBeg)+''')'+
                  ' and (e.date_action<'''+DateToStr(DtEnd)+''')'+
                  ' group by s.raon_cod';
*)
 dset_tmp.SelectSQL.Text:=' select o.fk_orders_regions reg_cod, count(distinct OrderNumber) cc'+
                          ' from orders o, excavations e'+
                          ' where (o.id=e.fk_excavations_orders) and (o.fk_orders_damageplace in (1,2))'+
                          ' and (e.fk_Excavations_Excwt in (6)) and (o.fk_orders_damagelocality in (3))'+
                          //' and (o.DateComing>='''+DateToStr(DtBeg)+''')'+
                          sDate+
                          ' and (DTime>='''+DateToStr(DtBeg)+''')'+
                          ' and (DTime<'''+DateToStr(DtEnd)+''')'+
                          ' group by o.fk_orders_regions';
 FillCol(18,dset_tmp,'reg_cod','cc');
 pind_Proc.Position:=pind_Proc.Position+6;
 {/Зеленая зона востановлено}


 {Зеленая зона не востановлено}
(*
 qry_temp.Sql.Text:='select s.raon_cod, count(distinct narjad_nom) cc from soob_wk s '+
                  'where (s.mesto_pv_c in (1,2)) and mestnst_c in (3) and (s.data_soob>='''+DateToStr(DtBeg)+''') '+
                  '  and Exists(select pole from excav e1 where e1.date_order=s.data_soob and e1.num_order=s.narjad_nom and e1.action in (1,2,3,9) and (e1.date_action<'''+DateToStr(DtEnd)+''')) '+
                  '  and not Exists(select pole from excav e1 where e1.date_order=s.data_soob and e1.num_order=s.narjad_nom and e1.action in (6) and (e1.date_action<'''+DateToStr(DtEnd)+''')) '+
                  ' group by s.raon_cod';
*)
 dset_tmp.SelectSQL.Text:=' select o.fk_orders_regions reg_cod, count(distinct OrderNumber) cc from orders o, excavations e1'+
                          ' where (o.fk_orders_damageplace in (1,2)) and (o.fk_orders_damagelocality in (3))'+
                          //' and (o.datecoming>='''+DateToStr(DtBeg)+''')'+
                          sDate +
                          ' and e1.fk_excavations_orders=o.id and e1.fk_excavations_excwt in (1,2,3,9) and (e1.DTime<'''+DateToStr(DtEnd)+''')'+
                          ' and (e1.DTime>='''+DateToStr(DtBeg)+''')'+
                          ' and o.id not in ('+
                          '    select e2.fk_excavations_orders'+
                          '    from excavations e2'+
                          '    where (e2.fk_excavations_excwt =6) and (e2.DTime<'''+DateToStr(DtEnd)+''')'+
                          '    and (e2.DTime>='''+DateToStr(DtBeg)+''')'+
                          '    )'+
                          ' group by o.fk_orders_regions';

 FillCol(19,dset_tmp,'reg_cod','cc');
 pind_Proc.Hide;
 {/Зеленая зона не востановлено}
end;

procedure TfmExcSprSheet.FormCreate(Sender: TObject);
var
  tr: TIBTransaction;
begin
  tr:=dset_tmp.Transaction;
  if tr.InTransaction then
    tr.Rollback;
  tr.StartTransaction;
  try
    FillGrid;
    tr.Commit;
  except
    on E: Exception do
    begin
      tr.Rollback;
      Exception.Create(E.Message+'(TfmExcSprSheet.FillGrid)');
    end;
  end;
end;

end.
